kind: pipeline
name: axylon

steps:
- name: compile
  image: fadlyas/kernel_dockerfile:latest
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
    ORIGIN:
      from_secret: ORIGIN
    DEFCONFIG: rova_defconfig
  commands:
  - apt update -qq -y && apt install -qq -y openjdk-11-jre-headless flex
  - git clone -qq --depth=1 https://github.com/rzlamrr/kernel_msm8917 axylon
  - cd axylon
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/rova49.sh
  - chmod +x rova49.sh
  - bash rova49.sh
