kind: pipeline
name: axylon

steps:
- name: compile
  image: fr3akyphantom/droid-builder:focal
  environment:
    TOKED:
      from_secret: TOKED
    CHATID:
      from_secret: CHATID
  commands:
  - git clone -qq --depth=1 https://github.com/greenforce-project/kernel_xiaomi_rova_sd425_4.9 -b android-4.9-q kernel
  - cd kernel
  - wget -q https://github.com/rzlamrr/scripts/raw/master/KERNEL/build.sh
  - chmod +x build.sh
  - bash build.sh
